### ISSUE TITLE
Support for GitHub Enterprise Server

### ISSUE THREAD

**Issue by jeffstoner** [chdsbd/vscode-github-code-owners#22]
Please add support for GitHub Enterprise Server. This is mainly for generating the correct URLs in `githubUserToUrl()`. I'll submit a PR for consideration.

**Comment by chdsbd** [comment]
Sounds like a great addition! I think we could probably add a [configuration option](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) or maybe figure out some way to look in the .git directory

**Comment by jeffstoner** [comment]
I had thought about trolling the .git/config for remotes but unless the URL is one of "github.com", "gitlab.com", or "bitbucket.org" there's no way I can tell if the remote is running GitHub Enterprise Server or Gitlab self-managed or Bitbucket Datacenter or Gogs/Gitea/whatever. While CODEOWNERS can use email addresses, when it comes to username and team names, there are syntax similarities between GitHub and Gitlab, such as "@username" but team name syntax does differ between GitHub, Gitlab, and Bitbucket.

The approach I've taken is to query the vscode workspace for the `github-enterprise.uri` setting from the GitHub Enterprise Server Authentication Provider extension which is baked in to VSCode (nothing else to install so no missing dependencies to worry about.) GitHub's official extensions (at least "Pull Requests and Issues" and "Actions") rely on that for working with GHES. So far, everything is working a treat.

**Comment by chdsbd** [comment]
If you want to make a PR, I can merge it

**Comment by chdsbd** [comment]
Fixed in #23
